/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.thecave.passcontrol.component.util;

import javax.swing.JPanel;

/**
 *
 * @author lopidio
 */
public class QueueElementInfoBig extends JPanel
{

    public QueueElementInfoBig( String clientName, String queueName, String userPass, String balconyName )
    {
        initComponents();

        txtFila.setText(queueName);
        txtNome.setText(clientName);
        txtGuiche.setText(balconyName);
        txtSenha.setText(userPass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSeparator1 = new javax.swing.JSeparator();
        lblGuiche = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtFila = new javax.swing.JLabel();
        txtGuiche = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 232, 29));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setForeground(new java.awt.Color(255, 100, 60));
        setMaximumSize(new java.awt.Dimension(350, 210));
        setMinimumSize(new java.awt.Dimension(350, 210));
        setPreferredSize(new java.awt.Dimension(350, 210));
        setLayout(null);

        jSeparator1.setToolTipText("");
        add(jSeparator1);
        jSeparator1.setBounds(20, 80, 320, 14);

        lblGuiche.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblGuiche.setText("Guiche:");
        add(lblGuiche);
        lblGuiche.setBounds(160, 10, 70, 24);

        lblFila.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFila.setText("Fila:");
        add(lblFila);
        lblFila.setBounds(10, 90, 40, 18);

        lblNome.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNome.setText("Nome do cliente:");
        add(lblNome);
        lblNome.setBounds(0, 150, 140, 18);

        txtNome.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNome.setText("Leudinho");
        add(txtNome);
        txtNome.setBounds(0, 180, 350, 19);

        txtFila.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        txtFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFila.setText("Prioritária");
        add(txtFila);
        txtFila.setBounds(0, 110, 350, 47);

        txtGuiche.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtGuiche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGuiche.setText("B13");
        add(txtGuiche);
        txtGuiche.setBounds(190, 30, 150, 40);

        lblSenha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblSenha.setText("Senha:");
        add(lblSenha);
        lblSenha.setBounds(10, 10, 60, 24);

        txtSenha.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSenha.setText("48");
        add(txtSenha);
        txtSenha.setBounds(20, 30, 150, 40);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFila;
    private javax.swing.JLabel lblGuiche;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel txtFila;
    private javax.swing.JLabel txtGuiche;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
