package br.com.thecave.passcontrol.component.util;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author lopidio
 */
public class QueueElementInfo extends JPanel
{

    private static class FadeInOutAction implements ActionListener
    {

        Timer timer = new Timer(0, this);
        private float DELTA;
        private float alpha;
        private JPanel jPanel;

        FadeInOutAction( JPanel jPanel, float DELTA ) throws Exception
        {
            this.DELTA = DELTA;
            this.jPanel = jPanel;

            if ( DELTA < 0 )
            {
                alpha = 1f;
            }
            else if ( DELTA > 0 )
            {
                alpha = 0;
            }
            else
            {
                throw new Exception("Delta inválido");
            }
            timer.start();
        }

        @Override
        public void actionPerformed( ActionEvent ae )
        {
            alpha += DELTA;
            if ( alpha < 0 || alpha > 1 )
            {
                timer.restart();
                if ( DELTA < 0 )
                {
                    alpha = 1f;
                }
                else if ( DELTA > 0 )
                {
                    alpha = 0;
                }
            }
            jPanel.repaint();
        }

        public float getAlpha()
        {
            return alpha;
        }

        public boolean isRunning()
        {
            return timer.isRunning();
        }
    }
    FadeInOutAction fader = null;
    
    private String clientName;
    private String queueName;
    private String balconyName;
    private String userPass;
    

    public QueueElementInfo( String clientName, String queueName, String userPass, String balconyName )
    {

        initComponents();
        this.clientName = clientName;
        this.queueName = queueName;
        this.balconyName = balconyName;
        this.userPass = userPass;

        txtFila.setText(queueName);
        txtNome.setText(clientName);
        txtSenha.setText(userPass);
        txtGuiche.setText(balconyName);

    }

    public void fadeIn( float DELTA ) throws Exception
    {
        fader = new FadeInOutAction(this, Math.abs(DELTA));

    }

    @Override
    protected void paintComponent( Graphics g )
    {
        super.paintComponent(g);

        if ( false && fader != null && fader.isRunning() )
        {
            Graphics2D g2d = (Graphics2D) g;
            g2d.setColor(new Color(g2d.getColor().getRed(), g2d.getColor().getGreen(), g2d.getColor().getBlue(), fader.getAlpha() * 255));
        }
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
        txtNome.setText(clientName);
    }

    public String getQueueName() {
        return queueName;
    }

    public void setQueueName(String queueName) {
        this.queueName = queueName;
        txtFila.setText(queueName);
    }

    public String getBalconyName() {
        return balconyName;
        
    }

    public void setBalconyName(String balconyName) {
        this.balconyName = balconyName;
        txtGuiche.setText(balconyName);        
    }

    public String getUserPass() {
        return userPass;
    }

    public void setUserPass(String userPass) {
        this.userPass = userPass;
        txtSenha.setText(userPass);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSeparator1 = new javax.swing.JSeparator();
        lblGuiche = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtFila = new javax.swing.JLabel();
        txtGuiche = new javax.swing.JLabel();
        lblSenha1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 232, 29));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setForeground(new java.awt.Color(255, 100, 60));
        setMaximumSize(new java.awt.Dimension(250, 150));
        setMinimumSize(new java.awt.Dimension(250, 150));
        setPreferredSize(new java.awt.Dimension(250, 95));
        setLayout(null);

        jSeparator1.setToolTipText("");
        add(jSeparator1);
        jSeparator1.setBounds(10, 50, 260, 14);

        lblGuiche.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblGuiche.setText("Guichê:");
        add(lblGuiche);
        lblGuiche.setBounds(120, 10, 50, 16);

        lblFila.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblFila.setText("Fila:");
        add(lblFila);
        lblFila.setBounds(10, 50, 27, 18);

        lblNome.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblNome.setText("Nome do cliente:");
        add(lblNome);
        lblNome.setBounds(10, 90, 118, 18);

        txtNome.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNome.setText("Leudinho");
        add(txtNome);
        txtNome.setBounds(0, 120, 280, 19);

        txtFila.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFila.setText("Prioritária");
        add(txtFila);
        txtFila.setBounds(20, 60, 250, 32);

        txtGuiche.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        txtGuiche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGuiche.setText("B13");
        add(txtGuiche);
        txtGuiche.setBounds(170, 10, 100, 40);

        lblSenha1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSenha1.setText("Senha:");
        add(lblSenha1);
        lblSenha1.setBounds(10, 10, 39, 16);

        txtSenha.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        txtSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSenha.setText("43");
        add(txtSenha);
        txtSenha.setBounds(0, 10, 160, 40);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFila;
    private javax.swing.JLabel lblGuiche;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JLabel txtFila;
    private javax.swing.JLabel txtGuiche;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
