/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.thecave.passcontrol.component.util;

import br.com.thecave.passcontrol.utils.PassControlFont;
import java.awt.Font;
import javax.swing.JPanel;

/**
 *
 * @author lopidio
 */
public class QueueElementInfoBig extends JPanel
{

    public QueueElementInfoBig( String clientName, String queueName, String userPass, String balconyName )
    {
        initComponents();

        txtFila.setText(queueName);
        txtNome.setText(clientName);
        txtGuiche.setText(balconyName);
        txtSenha.setText(userPass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblGuiche = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtFila = new javax.swing.JLabel();
        txtGuiche = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 232, 29));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setForeground(new java.awt.Color(255, 100, 60));
        setMaximumSize(new java.awt.Dimension(440, 256));
        setMinimumSize(new java.awt.Dimension(440, 256));
        setPreferredSize(new java.awt.Dimension(440, 256));
        setLayout(null);

        jSeparator1.setToolTipText("");
        add(jSeparator1);
        jSeparator1.setBounds(20, 120, 400, 14);

        lblGuiche.setFont(new PassControlFont().getSizedFont(18).deriveFont(Font.BOLD));
        lblGuiche.setText("Guichê:");
        add(lblGuiche);
        lblGuiche.setBounds(210, 10, 220, 40);

        lblFila.setFont(new PassControlFont().getSizedFont(18).deriveFont(Font.BOLD));
        lblFila.setText("Fila:");
        add(lblFila);
        lblFila.setBounds(10, 138, 130, 50);

        lblNome.setFont(new PassControlFont().getSizedFont(18).deriveFont(Font.BOLD));
        lblNome.setText("Cliente:");
        add(lblNome);
        lblNome.setBounds(10, 198, 120, 50);

        txtNome.setFont(new PassControlFont().getSizedFont(24));
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNome.setText("Leudinho");
        add(txtNome);
        txtNome.setBounds(130, 200, 300, 40);

        txtFila.setFont(new PassControlFont().getSizedFont(24));
        txtFila.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtFila.setText("Prioritária");
        add(txtFila);
        txtFila.setBounds(130, 140, 300, 50);

        txtGuiche.setFont(new PassControlFont().getSizedFont(38).deriveFont(Font.BOLD));
        txtGuiche.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGuiche.setText("B13");
        add(txtGuiche);
        txtGuiche.setBounds(210, 50, 220, 60);

        lblSenha.setFont(new PassControlFont().getSizedFont(18).deriveFont(Font.BOLD));
        lblSenha.setText("Senha:");
        add(lblSenha);
        lblSenha.setBounds(10, 8, 190, 40);

        txtSenha.setFont(new PassControlFont().getSizedFont(38).deriveFont(Font.BOLD));
        txtSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSenha.setText("48");
        add(txtSenha);
        txtSenha.setBounds(10, 50, 210, 60);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFila;
    private javax.swing.JLabel lblGuiche;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel txtFila;
    private javax.swing.JLabel txtGuiche;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
