/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.thecave.passcontrol.screens;

import javax.swing.JPanel;

/**
 *
 * @author lopidio
 */
public class QueueElementInfo extends JPanel 
{


    public QueueElementInfo(String clientName, String queueName, String userPass) {
        
        initComponents();
        
        txtFila.setText(queueName);
        txtNome.setText(clientName);
        txtSenha.setText(userPass);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblSenha = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtFila = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 232, 29));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setForeground(new java.awt.Color(255, 100, 60));
        setMaximumSize(new java.awt.Dimension(841, 403));
        setMinimumSize(new java.awt.Dimension(841, 403));
        setLayout(null);

        jSeparator1.setToolTipText("");
        add(jSeparator1);
        jSeparator1.setBounds(30, 120, 350, 14);

        lblSenha.setText("Senha:");
        add(lblSenha);
        lblSenha.setBounds(10, 20, 47, 18);

        lblFila.setText("Fila:");
        add(lblFila);
        lblFila.setBounds(10, 140, 27, 18);

        lblNome.setText("Nome do cliente:");
        add(lblNome);
        lblNome.setBounds(10, 240, 118, 18);

        txtNome.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNome.setText("Leudinho");
        add(txtNome);
        txtNome.setBounds(0, 280, 400, 19);

        txtFila.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFila.setText("Prioritária");
        add(txtFila);
        txtFila.setBounds(11, 160, 390, 56);

        txtSenha.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        txtSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSenha.setText("43");
        add(txtSenha);
        txtSenha.setBounds(10, 50, 380, 70);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFila;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel txtFila;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
