package br.com.thecave.passcontrol.screens;

import br.com.thecave.passcontrol.component.util.QueueElementInfo;
import br.com.thecave.passcontrol.controller.Main;
import br.com.thecave.passcontrol.controller.QueuePushController;
import br.com.thecave.passcontrol.topbar.MainTopBar;
import br.com.thecave.passcontrolserver.db.bean.ClientBean;
import br.com.thecave.passcontrolserver.db.bean.ServiceBean;
import br.com.thecave.passcontrolserver.db.bean.UserBean;
import br.com.thecave.passcontrolserver.util.IValidation;
import br.com.thecave.passcontrolserver.util.ValidationPerform;
import br.com.thecave.passcontrolserver.util.validations.ValidIsEmpty;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author Arleudo
 */
public class QueuePushScreen extends PassControlPanel
{

    QueuePushController controller = null;
    ClientBean clientBean;
    ServiceBean serviceBean;
    private boolean ready;

    /**
     * Creates new form AdminScreen
     */
    public QueuePushScreen()
    {
        super("Escolha de Serviços", new QueuePushController());
        this.controller = (QueuePushController) getPanelController();
        initComponents();
        jpNovoCliente.setVisible(false);
        jpNovoAtendimento.setVisible(false);
        jmVoltar.setVisible(false);
        jSeparator1.setVisible(false);
        tfNomeNovoAtendimento.setEnabled(false);
        tfTelefoneNovoAtendimento.setEnabled(false);
        jpQueueInfo.setVisible(false);
        
        jpQueueInfo.setLayout(new BoxLayout(jpQueueInfo, BoxLayout.Y_AXIS));
        
        jlCadastroClienteErro.setVisible(false);
        jlNomeAtendimentoErro.setVisible(false);
        jlTelefoneAtendimentoErro.setVisible(false);
        jlTelefoneClienteErro.setVisible(false);
        jlNomeClienteErro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jmChooseService = new javax.swing.JMenu();
        jmNovoCliente = new javax.swing.JMenuItem();
        jmNovoAtendimento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmVoltar = new javax.swing.JMenuItem();
        jpQueueInfo = new javax.swing.JPanel();
        jlAdminPic = new javax.swing.JLabel();
        jpBarraLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbNovoCliente = new javax.swing.JButton();
        jbNovoAtendimento = new javax.swing.JButton();
        jpNovoAtendimento = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfCadastroNovoAtendimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNomeNovoAtendimento = new javax.swing.JTextField();
        tfTelefoneNovoAtendimento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbServico = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jbInserirNovoAtendimento = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlNomeAtendimentoErro = new javax.swing.JLabel();
        jlTelefoneAtendimentoErro = new javax.swing.JLabel();
        jpNovoCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCadastroNovoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNomeNovoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTelefoneNovoCliente = new javax.swing.JTextField();
        jbInserirNovoCliente = new javax.swing.JButton();
        jlCadastroClienteErro = new javax.swing.JLabel();
        jlNomeClienteErro = new javax.swing.JLabel();
        jlTelefoneClienteErro = new javax.swing.JLabel();

        jmChooseService.setMnemonic('e');
        jmChooseService.setText("Recepção");
        jmChooseService.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        jmNovoCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmNovoCliente.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jmNovoCliente.setMnemonic('c');
        jmNovoCliente.setText("Novo cliente");
        jmNovoCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jmNovoClienteActionPerformed(evt);
            }
        });
        jmChooseService.add(jmNovoCliente);

        jmNovoAtendimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmNovoAtendimento.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jmNovoAtendimento.setMnemonic('a');
        jmNovoAtendimento.setText("Novo Atendimento");
        jmNovoAtendimento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jmNovoAtendimentoActionPerformed(evt);
            }
        });
        jmChooseService.add(jmNovoAtendimento);
        jmChooseService.add(jSeparator1);

        jmVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jmVoltar.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jmVoltar.setText("Voltar");
        jmVoltar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jmVoltarActionPerformed(evt);
            }
        });
        jmChooseService.add(jmVoltar);

        jpQueueInfo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpQueueInfoLayout = new javax.swing.GroupLayout(jpQueueInfo);
        jpQueueInfo.setLayout(jpQueueInfoLayout);
        jpQueueInfoLayout.setHorizontalGroup(
            jpQueueInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jpQueueInfoLayout.setVerticalGroup(
            jpQueueInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlAdminPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/queue_push_button.png"))); // NOI18N
        add(jlAdminPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 11, -1, -1));

        jpBarraLateral.setPreferredSize(new java.awt.Dimension(6, 0));

        javax.swing.GroupLayout jpBarraLateralLayout = new javax.swing.GroupLayout(jpBarraLateral);
        jpBarraLateral.setLayout(jpBarraLateralLayout);
        jpBarraLateralLayout.setHorizontalGroup(
            jpBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jpBarraLateralLayout.setVerticalGroup(
            jpBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        add(jpBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 11, -1, 290));

        jLabel1.setBackground(new java.awt.Color(150, 150, 150));
        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(200, 200, 200));
        jLabel1.setText("RECEPÇÃO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 11, -1, -1));

        jbNovoCliente.setBackground(new java.awt.Color(45, 123, 142));
        jbNovoCliente.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jbNovoCliente.setText("Novo Cliente");
        jbNovoCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbNovoClienteActionPerformed(evt);
            }
        });
        add(jbNovoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 221, 37));

        jbNovoAtendimento.setBackground(new java.awt.Color(45, 123, 142));
        jbNovoAtendimento.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jbNovoAtendimento.setText("Novo Atendimento");
        jbNovoAtendimento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbNovoAtendimentoActionPerformed(evt);
            }
        });
        add(jbNovoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 221, 37));

        jpNovoAtendimento.setPreferredSize(new java.awt.Dimension(320, 196));

        jLabel5.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel5.setText("Cadastro:");

        tfCadastroNovoAtendimento.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        tfCadastroNovoAtendimento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfCadastroNovoAtendimentoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel7.setText("Nome:");

        tfNomeNovoAtendimento.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        tfTelefoneNovoAtendimento.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel8.setText("Telefone:");

        cbServico.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        cbServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel9.setText("Serviço:");

        jbInserirNovoAtendimento.setBackground(new java.awt.Color(45, 123, 142));
        jbInserirNovoAtendimento.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jbInserirNovoAtendimento.setText("Inserir");
        jbInserirNovoAtendimento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbInserirNovoAtendimentoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 191));
        jButton1.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Lupe_Small.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Lupe_Small_Clicked.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jlNomeAtendimentoErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/errovalid.png"))); // NOI18N

        jlTelefoneAtendimentoErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/errovalid.png"))); // NOI18N

        javax.swing.GroupLayout jpNovoAtendimentoLayout = new javax.swing.GroupLayout(jpNovoAtendimento);
        jpNovoAtendimento.setLayout(jpNovoAtendimentoLayout);
        jpNovoAtendimentoLayout.setHorizontalGroup(
            jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(tfCadastroNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(16, 16, 16)
                        .addComponent(tfTelefoneNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlTelefoneAtendimentoErro))
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20)
                        .addComponent(cbServico, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbInserirNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)
                        .addComponent(tfNomeNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNomeAtendimentoErro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpNovoAtendimentoLayout.setVerticalGroup(
            jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfCadastroNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeAtendimentoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomeNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(tfTelefoneNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefoneAtendimentoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpNovoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoAtendimentoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(cbServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbInserirNovoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpNovoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 320, 240));

        jLabel2.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel2.setText("Cadastro:");

        tfCadastroNovoCliente.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        tfCadastroNovoCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfCadastroNovoClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        tfNomeNovoCliente.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel4.setText("Telefone:");

        tfTelefoneNovoCliente.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        jbInserirNovoCliente.setBackground(new java.awt.Color(45, 123, 142));
        jbInserirNovoCliente.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jbInserirNovoCliente.setText("Inserir");
        jbInserirNovoCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbInserirNovoClienteActionPerformed(evt);
            }
        });

        jlCadastroClienteErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/errovalid.png"))); // NOI18N

        jlNomeClienteErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/errovalid.png"))); // NOI18N

        jlTelefoneClienteErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/errovalid.png"))); // NOI18N

        javax.swing.GroupLayout jpNovoClienteLayout = new javax.swing.GroupLayout(jpNovoCliente);
        jpNovoCliente.setLayout(jpNovoClienteLayout);
        jpNovoClienteLayout.setHorizontalGroup(
            jpNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovoClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoClienteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(tfCadastroNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCadastroClienteErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpNovoClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(tfTelefoneNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlTelefoneClienteErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbInserirNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpNovoClienteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(tfNomeNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNomeClienteErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jpNovoClienteLayout.setVerticalGroup(
            jpNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovoClienteLayout.createSequentialGroup()
                .addGroup(jpNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoClienteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addGroup(jpNovoClienteLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jpNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCadastroClienteErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCadastroNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jpNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(tfNomeNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeClienteErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpNovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(tfTelefoneNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefoneClienteErro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jbInserirNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpNovoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 320, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void jmNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNovoClienteActionPerformed
        novoCliente();
    }//GEN-LAST:event_jmNovoClienteActionPerformed

    private void jbNovoClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbNovoClienteActionPerformed
    {//GEN-HEADEREND:event_jbNovoClienteActionPerformed
        novoCliente();
    }//GEN-LAST:event_jbNovoClienteActionPerformed

    private void jbNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbNovoAtendimentoActionPerformed
    {//GEN-HEADEREND:event_jbNovoAtendimentoActionPerformed
        novoAtendimento();
    }//GEN-LAST:event_jbNovoAtendimentoActionPerformed

    private void jmNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmNovoAtendimentoActionPerformed
    {//GEN-HEADEREND:event_jmNovoAtendimentoActionPerformed
        novoAtendimento();
    }//GEN-LAST:event_jmNovoAtendimentoActionPerformed

    private void jmVoltarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmVoltarActionPerformed
    {//GEN-HEADEREND:event_jmVoltarActionPerformed
        Main.getInstance().getMainFrame().activatePassControlPanel(new QueuePushScreen());
        Main.getInstance().getMainFrame().activatePassControlTopBar(new MainTopBar());
    }//GEN-LAST:event_jmVoltarActionPerformed

    private void jbInserirNovoClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbInserirNovoClienteActionPerformed
    {//GEN-HEADEREND:event_jbInserirNovoClienteActionPerformed
        ClientBean bean = new ClientBean();
        // validar campos posteriormente
        String nomeCliente = tfNomeNovoCliente.getText();
        
        ArrayList<IValidation> validations = new ArrayList<>();        
        validations.add(new ValidIsEmpty());
        
        // validando o cadastro
        
        bean.setName(nomeCliente);
        bean.setRegister(tfCadastroNovoCliente.getText());
        bean.setTelefone(tfTelefoneNovoCliente.getText());
        controller.insertNewClient(bean);
        Main.getInstance().getMainFrame().activatePassControlPanel(new QueuePushScreen());
        Main.getInstance().getMainFrame().activatePassControlTopBar(new MainTopBar());
    }//GEN-LAST:event_jbInserirNovoClienteActionPerformed

    private void tfCadastroNovoClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfCadastroNovoClienteActionPerformed
    {//GEN-HEADEREND:event_tfCadastroNovoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCadastroNovoClienteActionPerformed

    private void tfCadastroNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfCadastroNovoAtendimentoActionPerformed
    {//GEN-HEADEREND:event_tfCadastroNovoAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCadastroNovoAtendimentoActionPerformed

    private void jbInserirNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbInserirNovoAtendimentoActionPerformed
    {//GEN-HEADEREND:event_jbInserirNovoAtendimentoActionPerformed
        inserirNovoAtendimento();
    }//GEN-LAST:event_jbInserirNovoAtendimentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        searchRegister();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbInserirNovoAtendimento;
    private javax.swing.JButton jbInserirNovoCliente;
    private javax.swing.JButton jbNovoAtendimento;
    private javax.swing.JButton jbNovoCliente;
    private javax.swing.JLabel jlAdminPic;
    private javax.swing.JLabel jlCadastroClienteErro;
    private javax.swing.JLabel jlNomeAtendimentoErro;
    private javax.swing.JLabel jlNomeClienteErro;
    private javax.swing.JLabel jlTelefoneAtendimentoErro;
    private javax.swing.JLabel jlTelefoneClienteErro;
    private javax.swing.JMenu jmChooseService;
    private javax.swing.JMenuItem jmNovoAtendimento;
    private javax.swing.JMenuItem jmNovoCliente;
    private javax.swing.JMenuItem jmVoltar;
    private javax.swing.JPanel jpBarraLateral;
    private javax.swing.JPanel jpNovoAtendimento;
    private javax.swing.JPanel jpNovoCliente;
    private javax.swing.JPanel jpQueueInfo;
    private javax.swing.JTextField tfCadastroNovoAtendimento;
    private javax.swing.JTextField tfCadastroNovoCliente;
    private javax.swing.JTextField tfNomeNovoAtendimento;
    private javax.swing.JTextField tfNomeNovoCliente;
    private javax.swing.JTextField tfTelefoneNovoAtendimento;
    private javax.swing.JTextField tfTelefoneNovoCliente;
    // End of variables declaration//GEN-END:variables

    @Override
    public ArrayList<JMenu> createMenuItems()
    {
        ArrayList<JMenu> retorno = new ArrayList<>();
        retorno.add(jmChooseService);

        return retorno;
    }

    private void novoCliente()
    {
        jpNovoCliente.setVisible(true);
        jbNovoAtendimento.setVisible(false);
        jbNovoCliente.setVisible(false);
        jSeparator1.setVisible(true);
        jmVoltar.setVisible(true);
        jmNovoAtendimento.setEnabled(false);
        jmNovoCliente.setEnabled(false);
        jpNovoCliente.setVisible(true);
        jpQueueInfo.setVisible(false);        
    }

    private void novoAtendimento()
    {
        jbNovoAtendimento.setVisible(false);
        jbNovoCliente.setVisible(false);
        jSeparator1.setVisible(true);
        jmVoltar.setVisible(true);
        jmNovoAtendimento.setEnabled(false);
        jmNovoCliente.setEnabled(false);
        jpNovoAtendimento.setVisible(true);
        jpQueueInfo.setVisible(false);
        
        // carregar os serviços e jogar no comboBox
        controller.defineServicos(cbServico);
                
    }

    public void showQueueElementInfo( QueueElementInfo elementInfo )
    {
        jpQueueInfo.add(elementInfo);
        jpQueueInfo.setVisible(true);
    }

    private void searchRegister()
    {
        clientBean = controller.loadRegister(tfCadastroNovoAtendimento.getText());
        if(clientBean != null)
        {
            tfCadastroNovoAtendimento.setText(clientBean.getRegister());
            tfNomeNovoAtendimento.setText(clientBean.getName());
            tfTelefoneNovoAtendimento.setText(clientBean.getTelefone());
        }
    }

    private void inserirNovoAtendimento()
    {
        // pegando o usuário logado
        UserBean userBean = Main.getInstance().getCurrentUser();
        // pegando o bean dos clientes
        String serviceName = "";
        if(cbServico.getSelectedItem() != null)
        {
            serviceName = cbServico.getSelectedItem().toString();
            serviceBean = controller.getService(serviceName);
            ready = true;
        }
        else
        {
            jlNomeAtendimentoErro.setVisible(true);
            jlNomeAtendimentoErro.setToolTipText("Campo não pode ser vazio!");
            ready = false;
        }
        
        if(ready)
        {
            if(controller.insertNewAtendimento(clientBean, userBean, serviceBean))
            {
                JOptionPane.showMessageDialog(null, "registro salvo com sucesso!");
                Main.getInstance().getMainFrame().activatePassControlPanel(new QueuePushScreen());
                Main.getInstance().getMainFrame().activatePassControlTopBar(new MainTopBar());
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Erro ao salvar registro!");
            }
        }
    }

    private void validarNome( String nomeCliente, ArrayList<IValidation> validations )
    {
        // validando o nome
        if( ValidationPerform.valid(nomeCliente, validations))
        {
            ready = true;
            jlNomeClienteErro.setVisible(false);
        }
        else
        {
            jlNomeClienteErro.setVisible(true);
            jlNomeClienteErro.setToolTipText(ValidationPerform.getComment());
            ready = false;
        }
    }
}
