package br.com.thecave.passcontrol.topbar;

import br.com.thecave.passcontrol.controller.BalconyLoginTopBarController;
import br.com.thecave.passcontrol.controller.Main;
import br.com.thecave.passcontrol.screens.BalconyScreen;
import br.com.thecave.passcontrolserver.db.bean.BalconyBean;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Arleudo
 */
public class BalconyLoginTopBar extends PassControlTopBar
{

    private BalconyLoginTopBarController balconyLoginTopBarController;
    private BalconyScreen screen;

    /**
     * Creates new form TopBar
     */
    public BalconyLoginTopBar()
    {
        super(new BalconyLoginTopBarController());
        initComponents();
        balconyLoginTopBarController = (BalconyLoginTopBarController) getPanelController();
        lbNameUser.setText(Main.getInstance().getCurrentUser().getName());
        jbConfirm.setEnabled(false);
        addPanelConnectionInfo();
//        balconyLoginTopBarController.defineCBNames(cbNumero);
    }

    public void enableConfirmButton()
    {
        jbConfirm.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIcon = new javax.swing.JLabel();
        jlBarra = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lbNameUser = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        cbNumero = new javax.swing.JComboBox();
        jbConfirm = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 191));
        setForeground(new java.awt.Color(0, 153, 191));
        setPreferredSize(new java.awt.Dimension(1376, 128));

        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_medium.png"))); // NOI18N

        jlBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barra.png"))); // NOI18N

        jlName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/name_system.png"))); // NOI18N

        lblUser.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuário:");

        lbNameUser.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbNameUser.setForeground(new java.awt.Color(255, 255, 255));
        lbNameUser.setText("Isso ira mudar");

        lbLogout.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 255, 255));
        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        lbLogout.setText("Logout");
        lbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });

        lbNumero.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(255, 255, 255));
        lbNumero.setText("Guichê:");

        cbNumero.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        cbNumero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jbConfirm.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jbConfirm.setText("OK");
        jbConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jlBarra)
                .addGap(12, 12, 12)
                .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(lbNumero)
                .addGap(14, 14, 14)
                .addComponent(cbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConfirm)
                .addGap(394, 394, 394)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(lbNameUser)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbLogout))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbNameUser)
                        .addGap(59, 59, 59)
                        .addComponent(lbLogout)))
                .addGap(174, 174, 174))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        Main.getInstance().getMainFrame().performLogoutAction();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void jbConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmActionPerformed
        balconyLoginTopBarController.confirmButtonPressed(cbNumero.getSelectedIndex());
        this.screen.initialize();
    }//GEN-LAST:event_jbConfirmActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbNumero;
    private javax.swing.JButton jbConfirm;
    private javax.swing.JLabel jlBarra;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbNameUser;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    public void setBalconyNumbers( ArrayList<BalconyBean> avaliableBalcony )
    {
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        for ( BalconyBean balconyBean : avaliableBalcony )
        {
            defaultComboBoxModel.addElement(balconyBean.getNumber());
        }
        cbNumero.setModel(defaultComboBoxModel);
    }

    @Override
    public void blockPassControlTopBar()
    {
        cbNumero.setEnabled(false);
        jbConfirm.setEnabled(false);
    }

    @Override
    public void unblockPassControlTopBar()
    {
        cbNumero.setEnabled(true);
        jbConfirm.setEnabled(true);
    }

    public void setScreen( BalconyScreen screen )
    {
        this.screen = screen;
    }
}
