package br.com.thecave.passcontrol.topbar;

import br.com.thecave.passcontrol.controler.BalconyTopBarIntroController;
import br.com.thecave.passcontrol.controler.Main;
import java.util.ArrayList;

/**
 *
 * @author Arleudo
 */
public class BalconyTopBarIntro extends PassControlTopBar
{
    private BalconyTopBarIntroController balconyTopBarIntroController;

    /**
     * Creates new form TopBar
     */
    public BalconyTopBarIntro() 
    {
        super(new BalconyTopBarIntroController());
        initComponents();
        balconyTopBarIntroController = (BalconyTopBarIntroController) getPanelController();
        lbNameUser.setText(Main.getInstance().getCurrentUser().getName());
        jbConfirm.setEnabled(false);
        addPanelConnectionInfo();
        
    }
    
    public void enableConfirmButton()
    {
        jbConfirm.setEnabled(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIcon = new javax.swing.JLabel();
        jlBarra = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lbNameUser = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        jlConnection = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        cbNumero = new javax.swing.JComboBox();
        cbTipo = new javax.swing.JComboBox();
        jbConfirm = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 191));
        setForeground(new java.awt.Color(0, 153, 191));
        setPreferredSize(new java.awt.Dimension(1376, 128));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_medium.png"))); // NOI18N
        add(jlIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 3, 106, 122));

        jlBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barra.png"))); // NOI18N
        add(jlBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 3, -1, 122));

        jlName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/name_system.png"))); // NOI18N
        add(jlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 3, 222, 122));

        lblUser.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuário:");
        add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1245, 3, -1, 22));

        lbNameUser.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbNameUser.setForeground(new java.awt.Color(255, 255, 255));
        lbNameUser.setText("Isso ira mudar");
        add(lbNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1245, 31, -1, -1));

        lbLogout.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(255, 255, 255));
        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        lbLogout.setText("Logout");
        lbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });
        add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1288, 108, -1, -1));

        jlConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/online.png"))); // NOI18N
        add(jlConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(1217, 3, -1, -1));

        lbTipo.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbTipo.setForeground(new java.awt.Color(255, 255, 255));
        lbTipo.setText("Tipo do Guichê:");
        add(lbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 57, -1, 28));

        lbNumero.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(255, 255, 255));
        lbNumero.setText("Número do Guichê:");
        add(lbNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 20, -1, 28));

        cbNumero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        add(cbNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 19, 185, 30));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo 1", "Tipo 2", "Tipo 3", "Tipo 4" }));
        add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 56, 185, 30));

        jbConfirm.setText("OK");
        jbConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmActionPerformed(evt);
            }
        });
        add(jbConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 92, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        balconyTopBarIntroController.performLogout();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void jbConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmActionPerformed
        balconyTopBarIntroController.confirmButtonPressed((String)cbNumero.getModel().getSelectedItem(), (String)cbTipo.getModel().getSelectedItem());
    }//GEN-LAST:event_jbConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbNumero;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JButton jbConfirm;
    private javax.swing.JLabel jlBarra;
    private javax.swing.JLabel jlConnection;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbNameUser;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    public void setConnectionIcon(boolean connectionStatus) 
    {
        //Altero a cor do ícone de conexão
        if (connectionStatus)
            jlConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/online.png"))); // NOI18N
        else
            jlConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/offline.png"))); // NOI18N        
    }

    public void setBalconyTypes(ArrayList<String> balconyTypes) {
        String[] strCast = new String[balconyTypes.size()];
        strCast = balconyTypes.toArray(strCast);
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(strCast));
    }

    public void setBalconyNumbers(ArrayList<String> balconyNumbers) {
        String[] strCast = new String[balconyNumbers.size()];
        strCast = balconyNumbers.toArray(strCast);
        cbNumero.setModel(new javax.swing.DefaultComboBoxModel(strCast));
    }

    @Override
    public void blockPassControlTopBar() 
    {
        cbNumero.setEnabled(false);
        cbTipo.setEnabled(false);
        jbConfirm.setEnabled(false);
    }

    @Override
    public void unblockPassControlTopBar() 
    {
        cbNumero.setEnabled(true);
        cbTipo.setEnabled(true);
        jbConfirm.setEnabled(true);
    }
    
}
