package br.com.thecave.passcontrol.topbar;

import br.com.thecave.passcontrol.controller.LoginTopBarController;
import javax.swing.JOptionPane;

/**
 *
 * @author Arleudo
 */
public class LoginTopBar extends PassControlTopBar
{

    private LoginTopBarController loginTopBarControler;

    /**
     * Creates new form TopBar
     */
    public LoginTopBar()
    {
        super(new LoginTopBarController());
        loginTopBarControler = (LoginTopBarController) getPanelController();
        initComponents();
        jlbErrorSenha.setVisible(false);
        jlErrorLogin.setVisible(false);
        addPanelConnectionInfo();
    }

    public void incorrectUser( String message )
    {
        JOptionPane.showMessageDialog(null, message, "Login não realizado", JOptionPane.ERROR_MESSAGE);
        jtfLogin.setText("");
        jtfSenha.setText("");
        verifyOkButton();
    }

    public String getUserName()
    {
        return jtfLogin.getText();
    }

    public String getUserPassword()
    {
        return new String(jtfSenha.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIcon = new javax.swing.JLabel();
        jlBarra = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jtfSenha = new javax.swing.JPasswordField();
        jbOk = new javax.swing.JButton();
        jlLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbForgottPassword = new javax.swing.JLabel();
        jlErrorLogin = new javax.swing.JLabel();
        jlbErrorSenha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 191));
        setForeground(new java.awt.Color(0, 153, 191));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(1376, 128));
        setPreferredSize(new java.awt.Dimension(1376, 128));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlIcon.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_medium.png"))); // NOI18N
        jlIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jlIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, 106, 116));

        jlBarra.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barra.png"))); // NOI18N
        add(jlBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 6, -1, 116));

        jlName.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/name_system.png"))); // NOI18N
        jlName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 6, 222, 116));

        jtfLogin.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jtfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfLoginKeyTyped(evt);
            }
        });
        add(jtfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1127, 9, 236, -1));

        jtfSenha.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jtfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSenhaKeyTyped(evt);
            }
        });
        add(jtfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1127, 37, 236, -1));

        jbOk.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jbOk.setText("OK");
        jbOk.setEnabled(false);
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });
        add(jbOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1294, 71, 70, -1));

        jlLogin.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(255, 255, 255));
        jlLogin.setText("Login:");
        add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1067, 37, -1, -1));

        lbForgottPassword.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        lbForgottPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbForgottPassword.setText("Esqueceu a senha?");
        lbForgottPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbForgottPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbForgottPasswordMouseClicked(evt);
            }
        });
        add(lbForgottPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1124, 78, -1, -1));

        jlErrorLogin.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jlErrorLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/errovalid.png"))); // NOI18N
        add(jlErrorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 9, -1, 20));

        jlbErrorSenha.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jlbErrorSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/errovalid.png"))); // NOI18N
        add(jlbErrorSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 37, -1, 28));
    }// </editor-fold>//GEN-END:initComponents

    private void lbForgottPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbForgottPasswordMouseClicked
        loginTopBarControler.resetPassword();
    }//GEN-LAST:event_lbForgottPasswordMouseClicked

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        loginTopBarControler.performLogin();
    }//GEN-LAST:event_jbOkActionPerformed

    private void jtfLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLoginKeyTyped
        verifyOkButton();
        if ( getUserName().length() >= 4 )
        {
            jlErrorLogin.setVisible(false);
        }
        else
        {
            jlErrorLogin.setVisible(true);
            jlErrorLogin.setToolTipText("Login Inválido!");
        }
    }//GEN-LAST:event_jtfLoginKeyTyped

    private void jtfSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSenhaKeyTyped
        verifyOkButton();
        if ( getUserPassword().length() >= 5 )
        {
            jlbErrorSenha.setVisible(false);
        }
        else
        {
            jlbErrorSenha.setVisible(true);
            jlbErrorSenha.setToolTipText("Senha Inválida!");
        }
    }//GEN-LAST:event_jtfSenhaKeyTyped

    private void verifyOkButton()
    {
        if ( getUserName().length() >= 4 && getUserPassword().length() >= 5 )
        {
            jbOk.setEnabled(true);
        }
        else
        {
            jbOk.setEnabled(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jlBarra;
    private javax.swing.JLabel jlErrorLogin;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlbErrorSenha;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JPasswordField jtfSenha;
    private javax.swing.JLabel lbForgottPassword;
    // End of variables declaration//GEN-END:variables
}
