/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.thecave.passcontrol.topbar;

import br.com.thecave.passcontrol.controller.ViewTopBarController;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author lopidio
 */
public class ViewTopBar extends PassControlTopBar
{
    ViewTopBarController viewTopBarController;

    /**
     * Creates new form ViewTopBar
     */
    public ViewTopBar() 
    {
        super(new ViewTopBarController());        
        initComponents();
        this.viewTopBarController = (ViewTopBarController)getPanelController();
        jpScrollableQueueInfoPanel.setLayout(new BoxLayout(jpScrollableQueueInfoPanel, BoxLayout.X_AXIS));
    }
    
    public JPanel getScrollableQueueInfoPanel()
    {
        return jpScrollableQueueInfoPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIcon = new javax.swing.JLabel();
        jlBarra = new javax.swing.JLabel();
        jlIcon1 = new javax.swing.JLabel();
        jlBarra1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpScrollableQueueInfoPanel = new javax.swing.JPanel();

        jlIcon.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_medium.png"))); // NOI18N

        jlBarra.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barra.png"))); // NOI18N

        setBackground(new java.awt.Color(0, 153, 193));

        jlIcon1.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_medium.png"))); // NOI18N

        jlBarra1.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlBarra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barra.png"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(0, 133, 163));
        jScrollPane1.setForeground(new java.awt.Color(0, 133, 163));

        javax.swing.GroupLayout jpScrollableQueueInfoPanelLayout = new javax.swing.GroupLayout(jpScrollableQueueInfoPanel);
        jpScrollableQueueInfoPanel.setLayout(jpScrollableQueueInfoPanelLayout);
        jpScrollableQueueInfoPanelLayout.setHorizontalGroup(
            jpScrollableQueueInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jpScrollableQueueInfoPanelLayout.setVerticalGroup(
            jpScrollableQueueInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpScrollableQueueInfoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlBarra1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlIcon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBarra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlBarra;
    private javax.swing.JLabel jlBarra1;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlIcon1;
    private javax.swing.JPanel jpScrollableQueueInfoPanel;
    // End of variables declaration//GEN-END:variables
}
