/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.thecave.passcontrol.topbar;

import br.com.thecave.passcontrol.controller.ViewTopBarController;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author lopidio
 */
public class ViewTopBar extends PassControlTopBar
{
    public final static int SCROLL_PANEL_WITDH = 1220;
    ViewTopBarController viewTopBarController;

    /**
     * Creates new form ViewTopBar
     */
    public ViewTopBar() 
    {
        super(new ViewTopBarController());        
        initComponents();
        this.viewTopBarController = (ViewTopBarController)getPanelController();
        jpScrollableQueueInfoPanel.setLayout(new BoxLayout(jpScrollableQueueInfoPanel, BoxLayout.X_AXIS));
    }
    
    public JPanel getScrollableQueueInfoPanel()
    {
        return jpScrollableQueueInfoPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIcon = new javax.swing.JLabel();
        jlBarra = new javax.swing.JLabel();
        jlBarra1 = new javax.swing.JLabel();
        jlIcon1 = new javax.swing.JLabel();
        jpOutterPanel = new javax.swing.JPanel();
        jpScrollableQueueInfoPanel = new javax.swing.JPanel();

        jlIcon.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_medium.png"))); // NOI18N

        jlBarra.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barra.png"))); // NOI18N

        setBackground(new java.awt.Color(0, 153, 193));
        setForeground(new java.awt.Color(0, 153, 193));
        setMaximumSize(new java.awt.Dimension(1376, 128));
        setMinimumSize(new java.awt.Dimension(1376, 128));
        setPreferredSize(new java.awt.Dimension(1376, 128));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlBarra1.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlBarra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barra.png"))); // NOI18N
        add(jlBarra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -10, 10, 160));

        jlIcon1.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jlIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_medium.png"))); // NOI18N
        add(jlIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 106, 116));

        jpOutterPanel.setBackground(new java.awt.Color(0, 153, 193));
        jpOutterPanel.setForeground(new java.awt.Color(0, 153, 193));
        jpOutterPanel.setMaximumSize(new java.awt.Dimension(1120, 95));
        jpOutterPanel.setMinimumSize(new java.awt.Dimension(1120, 95));
        jpOutterPanel.setPreferredSize(new java.awt.Dimension(1220, 95));

        jpScrollableQueueInfoPanel.setBackground(new java.awt.Color(0, 143, 193));

        javax.swing.GroupLayout jpScrollableQueueInfoPanelLayout = new javax.swing.GroupLayout(jpScrollableQueueInfoPanel);
        jpScrollableQueueInfoPanel.setLayout(jpScrollableQueueInfoPanelLayout);
        jpScrollableQueueInfoPanelLayout.setHorizontalGroup(
            jpScrollableQueueInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jpScrollableQueueInfoPanelLayout.setVerticalGroup(
            jpScrollableQueueInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpOutterPanelLayout = new javax.swing.GroupLayout(jpOutterPanel);
        jpOutterPanel.setLayout(jpOutterPanelLayout);
        jpOutterPanelLayout.setHorizontalGroup(
            jpOutterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpScrollableQueueInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpOutterPanelLayout.setVerticalGroup(
            jpOutterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOutterPanelLayout.createSequentialGroup()
                .addComponent(jpScrollableQueueInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jpOutterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1220, 130));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlBarra;
    private javax.swing.JLabel jlBarra1;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlIcon1;
    private javax.swing.JPanel jpOutterPanel;
    private javax.swing.JPanel jpScrollableQueueInfoPanel;
    // End of variables declaration//GEN-END:variables
}
